package com.zoro.springboot.entity;

public class Attach {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attach.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attach.fname
     *
     * @mbg.generated
     */
    private String fname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attach.ftype
     *
     * @mbg.generated
     */
    private String ftype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attach.authorId
     *
     * @mbg.generated
     */
    private Integer authorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attach.created
     *
     * @mbg.generated
     */
    private Integer created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attach.fkey
     *
     * @mbg.generated
     */
    private String fkey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attach.id
     *
     * @return the value of t_attach.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attach.id
     *
     * @param id the value for t_attach.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attach.fname
     *
     * @return the value of t_attach.fname
     *
     * @mbg.generated
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attach.fname
     *
     * @param fname the value for t_attach.fname
     *
     * @mbg.generated
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attach.ftype
     *
     * @return the value of t_attach.ftype
     *
     * @mbg.generated
     */
    public String getFtype() {
        return ftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attach.ftype
     *
     * @param ftype the value for t_attach.ftype
     *
     * @mbg.generated
     */
    public void setFtype(String ftype) {
        this.ftype = ftype == null ? null : ftype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attach.authorId
     *
     * @return the value of t_attach.authorId
     *
     * @mbg.generated
     */
    public Integer getAuthorid() {
        return authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attach.authorId
     *
     * @param authorid the value for t_attach.authorId
     *
     * @mbg.generated
     */
    public void setAuthorid(Integer authorid) {
        this.authorid = authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attach.created
     *
     * @return the value of t_attach.created
     *
     * @mbg.generated
     */
    public Integer getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attach.created
     *
     * @param created the value for t_attach.created
     *
     * @mbg.generated
     */
    public void setCreated(Integer created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attach.fkey
     *
     * @return the value of t_attach.fkey
     *
     * @mbg.generated
     */
    public String getFkey() {
        return fkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attach.fkey
     *
     * @param fkey the value for t_attach.fkey
     *
     * @mbg.generated
     */
    public void setFkey(String fkey) {
        this.fkey = fkey == null ? null : fkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Attach other = (Attach) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getFname() == null ? other.getFname() == null : this.getFname().equals(other.getFname()))
            && (this.getFtype() == null ? other.getFtype() == null : this.getFtype().equals(other.getFtype()))
            && (this.getAuthorid() == null ? other.getAuthorid() == null : this.getAuthorid().equals(other.getAuthorid()))
            && (this.getCreated() == null ? other.getCreated() == null : this.getCreated().equals(other.getCreated()))
            && (this.getFkey() == null ? other.getFkey() == null : this.getFkey().equals(other.getFkey()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFname() == null) ? 0 : getFname().hashCode());
        result = prime * result + ((getFtype() == null) ? 0 : getFtype().hashCode());
        result = prime * result + ((getAuthorid() == null) ? 0 : getAuthorid().hashCode());
        result = prime * result + ((getCreated() == null) ? 0 : getCreated().hashCode());
        result = prime * result + ((getFkey() == null) ? 0 : getFkey().hashCode());
        return result;
    }


}