package com.zoro.springboot.mapper;

import com.zoro.springboot.entity.Attach;
import com.zoro.springboot.entity.AttachExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttachMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbg.generated
     */
    long countByExample(AttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbg.generated
     */
    int deleteByExample(AttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbg.generated
     */
    int insert(Attach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbg.generated
     */
    int insertSelective(Attach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbg.generated
     */
    List<Attach> selectByExampleWithBLOBs(AttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbg.generated
     */
    List<Attach> selectByExample(AttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbg.generated
     */
    Attach selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Attach record, @Param("example") AttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Attach record, @Param("example") AttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Attach record, @Param("example") AttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Attach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Attach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Attach record);
}